[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"
channel = "nightly"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.14"
ratatui = "0.29.0"
unicode-width = "0.2.0"

[[bench]]
name = "solver"
harness = false
